# Generated by Django 5.1.3 on 2024-11-10 03:59

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15, validators=[users.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='spam',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[users.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[users.models.validate_phone_number]),
        ),
    ]
